# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29f0d8b55e1b2b5779dc4bc7fe3c6338e6be8ff02bbc08e9cd301c549789e4648099d179e9d84920291e2a5fc5bc4ea076b9bc2517aec9c9aabba7d5d9496065

test:
  secret_key_base: 43bacb9f109ddd9a4842c350bb480282e8fc0d11a50f3cbf6d9cbd448242dd5945b38e7707ce796bc164dea09c9e53fe822a47073b0f23ce2cee64b37edb0ffe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
